// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZqWDbvXssqkeNnKE7PmaKvKIewCFUdRo',
    appId: '1:749887029696:web:e6df241d613e6b1687c825',
    messagingSenderId: '749887029696',
    projectId: 'ynab-f3637',
    authDomain: 'ynab-f3637.firebaseapp.com',
    storageBucket: 'ynab-f3637.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBQq3c2wA7iNlQQOS2ax8JiDABYAJoaQ',
    appId: '1:749887029696:android:379314b9b6a5651487c825',
    messagingSenderId: '749887029696',
    projectId: 'ynab-f3637',
    storageBucket: 'ynab-f3637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSZpaEE94qjVVRtsO5R4jT3P5Poo-8r7o',
    appId: '1:749887029696:ios:77d4eb367b31999687c825',
    messagingSenderId: '749887029696',
    projectId: 'ynab-f3637',
    storageBucket: 'ynab-f3637.firebasestorage.app',
    iosBundleId: 'com.example.ynab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSZpaEE94qjVVRtsO5R4jT3P5Poo-8r7o',
    appId: '1:749887029696:ios:77d4eb367b31999687c825',
    messagingSenderId: '749887029696',
    projectId: 'ynab-f3637',
    storageBucket: 'ynab-f3637.firebasestorage.app',
    iosBundleId: 'com.example.ynab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZqWDbvXssqkeNnKE7PmaKvKIewCFUdRo',
    appId: '1:749887029696:web:a8354c13407ce34487c825',
    messagingSenderId: '749887029696',
    projectId: 'ynab-f3637',
    authDomain: 'ynab-f3637.firebaseapp.com',
    storageBucket: 'ynab-f3637.firebasestorage.app',
  );
}
